
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package aai;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-05-09T08:42:25.947-05:00
 * Generated source version: 3.0.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "AaiServiceService",
                      portName = "AaiServicePort",
                      targetNamespace = "http://aai/",
                      wsdlLocation = "file:/Users/petecarapetyan/work/jammazwan/aai_contract_first/src/main/resources/wsdl/aai.wsdl",
                      endpointInterface = "aai.AaiService")
                      
public class AaiServicePortImpl implements AaiService {

    private static final Logger LOG = Logger.getLogger(AaiServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see aai.AaiService#fixes(aai.Car  arg0 )*
     */
    public aai.Mechanic fixes(aai.Car arg0) { 
        LOG.info("Executing operation fixes");
        System.out.println(arg0);
        try {
            aai.Mechanic _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
